apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-model-storage-pvc
  namespace: lyric-professor
  labels:
    app: smollm3-distributed-finetuning
    role: master-storage
spec:
  accessModes:
    - ReadWriteOnce  # Only master pod needs this
  resources:
    requests:
      storage: 110Gi  # Storage for trained models and artifacts
  storageClassName: gp3-csi  # Use appropriate storage class for your cluster